[package]
name = "discord_gm_bot"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
ed25519-dalek = "2.2.0"
env_logger = "0.11.8"
hex = "0.4.3"
log = "0.4.28"
tokio = { version = "1.48.0", features = ["full"] } 
